[workspace]
members = ["switcherooctl", "switcheroo-daemon", "switcheroo-common"]
resolver = "2"

[workspace.package]
version = "0.1.2"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/LuMarans30/switcheroo-control-rs"

[workspace.dependencies]
color-eyre = "0.6.5"
zbus = "4.0"
tokio = { version = "1.52.3", features = ["full"] }
clap = { version = "4.6.1", features = ["derive"] }
switcheroo-common = { path = "switcheroo-common", version = "0.1.2" }

[workspace.lints.clippy]
pedantic = "warn"
