[package]
name = "switcherooctl"
description = "CLI client for switcheroo-control-rs used to list GPUs and launch binaries on a specific GPU"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "switcherooctl"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
switcheroo-common = { workspace = true }
zbus = { workspace = true }
color-eyre = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }

[lints]
workspace = true
