[package]
name = "switcherooctl"
description = "CLI utility to list GPUs and launch binaries using a specific GPU"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "switcherooctl"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
switcheroo-common = { path = "../switcheroo-common" }
zbus = { workspace = true }
color-eyre = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
