[package]
name = "switcheroo-daemon"
description = "Daemon that monitors GPUs and exposes their info over D-Bus"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
switcheroo-common = { workspace = true }
zbus = { workspace = true }
color-eyre = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
udev = { version = "0.9.3", features = ["sync"] }
regex = "1.12.4"
nix = { version = "0.31.3", features = ["ioctl"] }
futures-lite = "2.6.1"

[lints]
workspace = true
