name: Rust Clippy Analysis

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    schedule:
        - cron: "33 9 * * 4"

jobs:
    rust-clippy-analyze:
        name: Run rust-clippy analyzing
        runs-on: ubuntu-latest
        env:
            FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
        permissions:
            contents: read
            security-events: write
            actions: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy

            - name: Install required cargo tools
              run: cargo install clippy-sarif sarif-fmt

            - name: Run rust-clippy
              run: |
                  cargo clippy \
                    --all-features \
                    --message-format=json \
                    -- -W clippy::pedantic |
                    clippy-sarif |
                    tee rust-clippy-results.sarif |
                    sarif-fmt
              continue-on-error: true

            - name: Upload analysis results to GitHub
              uses: github/codeql-action/upload-sarif@v4
              with:
                  sarif_file: rust-clippy-results.sarif
                  wait-for-processing: true
